# Generated by Django 5.0.6 on 2026-02-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_id", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("available_units", models.PositiveIntegerField()),
            ],
            options={
                "unique_together": {("dish_id", "date")},
            },
        ),
    ]
