# Generated by Django 5.2.11 on 2026-03-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DailyProduction",
            new_name="DailyProductionModel",
        ),
    ]
