events {}

http {
    server {
        listen 80;

        # Django (todo lo viejo)
        location / {
            proxy_pass http://django:8000;
        }

        # Flask (payments nuevo)
        location /api/v2/payments/ {
            proxy_pass http://flask:5000;
        }
    }
}