# Generated by Django 5.2.11 on 2026-03-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productmodel",
            new_name="dishes_prod_name_82265c_idx",
            old_name="dishes_productmodel_name_idx",
        ),
    ]
