# Generated by Django 5.2.11 on 2026-03-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="paymentmodel",
            index=models.Index(
                fields=["order_id"], name="payments_pa_order_i_cffffb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmodel",
            index=models.Index(fields=["status"], name="payments_pa_status_e00f30_idx"),
        ),
    ]
