events { worker_connections 1024; }

http {
  upstream django    { server django:8000; }
  upstream flask_ms  { server recommendations:5001; }

  server {
    listen 80;

    # Microservicio Flask
    location /api/v2/ {
      proxy_pass http://flask_ms;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /health/ {
      proxy_pass http://flask_ms;
      proxy_set_header Host $host;
    }

    # Django
    location / {
      proxy_pass http://django;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_read_timeout 60s;
    }
  }
}